repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        types_or:
          - python
          - jupyter
        args: ["--fix", "--show-fixes"]
      - id: ruff-format
        types_or:
          - python
          - jupyter
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.11.2'
    hooks:
    - id: mypy
      pass_filenames: false
      args:
        - .
      additional_dependencies:
        - click
        - fastapi
        - httpx
        - pydantic
        - pydantic_settings
        - pytest
        - respx
        - rich
        - types-pyyaml
