[tool.black]
line-length = 88
target-version = ['py39']

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
# GitHub Actions make it hard for pytest to conlcude it should use colors, due
# to this we explicitly make it do so. This is related to:
# https://github.com/actions/runner/issues/241
addopts = '--color=yes'

[tool.mypy]
warn_unused_configs = true
exclude = "kbatch(-proxy)?/(docker|setup.py|hub)|docs/source|jupyterhub_config.py"
mypy_path = "kbatch-proxy:kbatch"


[[tool.mypy.overrides]]
module = [
    "escapism",
    "sqlalchemy",
    "jupyterhub",
    "jupyterhub.services",
    "jupyterhub.services.auth",
    "kubernetes",
    "kubernetes.config",
    "kubernetes.client",
    "kubernetes.watch",
    "kubernetes.client.models",
]
ignore_missing_imports = true

[tool.tbump.version]
current = "0.5.0.dev0"

# Example of a semver regexp.
# Make sure this matches current_version before
# using tbump
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  (?P<pre>((a|b|rc)\d+)|)
  \.?
  (?P<dev>(?<=\.)dev\d*|)
  '''

[tool.tbump.git]
message_template = "Bump to {new_version}"
tag_template = "{new_version}"

[[tool.tbump.file]]
src = "kbatch/pyproject.toml"
search = 'version = "{current_version}"'

[[tool.tbump.file]]
src = "kbatch/kbatch/__init__.py"
search = '__version__ = "{current_version}"'

[[tool.tbump.file]]
src = "kbatch-proxy/pyproject.toml"
search = 'version = "{current_version}"'

[[tool.tbump.file]]
src = "docs/source/conf.py"
search = 'release = "{current_version}"'
