# generated by datamodel-codegen:
#   filename:  http://127.0.0.1:8080/openapi/v2
#   timestamp: 2021-11-01T16:10:27+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Model(BaseModel):
    __root__: Any
