name: Create and publish a Docker image

on:
  release:
    types:
      - created

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-proxy

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: kbatch-proxy
          file: kbatch-proxy/docker/production/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: "kbatch-proxy/helm"
          charts_url: https://kbatch-dev.github.io/kbatch/
          linting: "off"
          chart_version: ${{ steps.get_version.outputs.VERSION }}

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install release dependencies
        run: |
          python -m pip install --upgrade build twine

      - name: Build and publish kbatch
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.KBATCH_PYPI_PASSWORD }}
        run: |
          cd kbatch
          python -m build
          twine upload dist/*
          cd ..

          cd kbatch-server
          python -m build
          twine upload dist/*

      - name: Build and publish kbatch-proxy
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.KBATCH_PROXY_PYPI_PASSWORD }}
        run: |
          cd kbatch
          python -m build
          twine upload dist/*
          cd ..

          cd kbatch-server
          python -m build
          twine upload dist/*