name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install release dependencies
        run: |
          python -m pip install --upgrade build twine

      - name: Build and publish package
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USER }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          cd kbatch
          python -m build
          twine upload dist/*
          cd ..

          cd kbatch-server
          python -m build
          twine upload dist/*